// Import React and the React DOM renderer.
import React from "react";
import ReactDOM from "react-dom/client";

// Import Bootstrap's stylesheet so React Bootstrap components are styled.
import "bootstrap/dist/css/bootstrap.min.css";

// Import the main application component and performance utility.
import App from "./App";
import reportWebVitals from "./reportWebVitals";

// Create the React root and render the application.
const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Optional performance measurement helper generated by Create React App.
reportWebVitals();
